[package]
name = "vaultctx"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
