[package]
name = "vaultctx"
version = "1.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
shellexpand = "3.1.0"
users = "0.11.0"
skim = "0.9"