---
- name: dummy_vault
  address: "https://vault:8200"
  token: hvs.abcdefghij1234567890
  cacert: /tls/vaultca.crt
  capath: /tls
  client_cert: /tls/vault.crt
  client_key: /tls/vault.key
  client_timeout: 30
  cluster_addr: "https://vault:8201"
  format: json
  license: ""
  license_path: ""
  log_level: info
  max_retries: 2
  redirect_addr: ""
  skip_verify: false
  tls_server_name: vault.local
  cli_no_color: false
  rate_limit: 0
  namespace: ""
  srv_lookup: true
  mfa: ""
  http_proxy: ""
  proxy_addr: ""
  disable_redirects: false